sudo: required
services:
  - docker

before_install:
  - docker build -t omeraslam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true omeraslam/react-test npm test

after_success:
  - docker build -t omeraslam/multi-client ./client
  - docker build -t omeraslam/multi-nginx ./nginx
  - docker build -t omeraslam/multi-server ./server
  - docker build -t omeraslam/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push omeraslam/multi-client
  - docker push omeraslam/multi-nginx
  - docker push omeraslam/multi-server
  - docker push omeraslam/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-564738772363"
  bucket-path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY