sudo: required
services:
  - docker

before_install:
  - docker build -t omeraslam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true omeraslam/react-test npm test

after_success:
  - docker build -t omeraslam/multi-client ./client
  - docker build -t omeraslam/multi-nginx ./nginx
  - docker build -t omeraslam/multi-server ./server
  - docker build -t omeraslam/multi-worker ./worker